# Data

In [3]:
!pip install indic-nlp-library huggingface_hub pandas matplotlib numpy scipy

Collecting indic-nlp-library
  Downloading indic_nlp_library-0.92-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.7.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Collecting sphinx-argparse (from indic-nlp-library)
  Downloading sphinx_argparse-0.5.2-py3-none-any.whl.metadata (3.7 kB)
Collecting sphinx-rtd-theme (from indic-nlp-library)
  Downloading sphinx_rtd_theme-3.1.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting morfessor (from indic-nlp-library)
  Downloading Morfessor-2.0.6-py3-none-any.whl.metadata (628 bytes)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sphinx>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from sphinx-argparse->indic-nlp-library) (8.2.3)
Requirement already satisfied: docutils>=0.19 in /usr/local/lib/python3.12/dist-packages (from sphinx-argparse->indic-nlp-library) (0.21.2)
Collecting sphinxcontrib-jquery<5,>=4 (from sphinx-rtd-theme->indic-nlp-library)
  Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.6)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.1)
Requirement already satisfied: babel>=2.13 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.18.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.4)
Requirement already satisfied: roman-numerals-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.5.0)
Requirement already satisfied: roman-numerals==4.1.0 in /usr/local/lib/python3.12/dist-packages (from roman-numerals-py>=1.0.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (4.1.0)
Downloading indic_nlp_library-0.92-py3-none-any.whl (40 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 4.0 MB/s eta 0:00:00
Downloading Morfessor-2.0.6-py3-none-any.whl (35 kB)
Downloading sphinx_argparse-0.5.2-py3-none-any.whl (12 kB)
Downloading sphinx_rtd_theme-3.1.0-py2.py3-none-any.whl (7.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 127.5 MB/s eta 0:00:00
Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 15.9 MB/s eta 0:00:00
Installing collected packages: morfessor, sphinxcontrib-jquery, sphinx-argparse, sphinx-rtd-theme, indic-nlp-library
Successfully installed indic-nlp-library-0.92 morfessor-2.0.6 sphinx-argparse-0.5.2 sphinx-rtd-theme-3.1.0 sphinxcontrib-jquery-4.1

In [2]:
import indicnlp
import huggingface_hub
import pandas as pd
import matplotlib
import numpy as np
import scipy

print("indic-nlp-library:", getattr(indicnlp, "__version__", "version not exposed"))
print("huggingface_hub:", huggingface_hub.__version__)
print("pandas:", pd.__version__)
print("matplotlib:", matplotlib.__version__)
print("numpy:", np.__version__)
print("scipy:", scipy.__version__)

indic-nlp-library: 0.92
huggingface_hub: 1.7.1
pandas: 2.2.2
matplotlib: 3.10.0
numpy: 2.0.2
scipy: 1.16.3

In [1]:
!pip install fasttext

Collecting fasttext
  Downloading fasttext-0.9.3.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 7.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pybind11>=2.2 (from fasttext)
  Using cached pybind11-3.0.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from fasttext) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fasttext) (2.0.2)
Using cached pybind11-3.0.2-py3-none-any.whl (310 kB)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (pyproject.toml) ... done
  Created wheel for fasttext: filename=fasttext-0.9.3-cp312-cp312-linux_x86_64.whl size=4647419 sha256=3b37cbf468c8caf2e94d39b04f9d20bde6771587f4335d6df198832421712d13
  Stored in directory: /root/.cache/pip/wheels/20/27/95/a7baf1b435f1cbde017cabdf1e9688526d2b0e929255a359c6
Successfully built fasttext
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.3 pybind11-3.0.2

In [4]:
import torch
import torch.nn as nn
import json
import pandas as pd
import numpy as np
from indicnlp.tokenize import indic_tokenize
import string
import spacy
nlp = spacy.load("en_core_web_sm")
import pickle
from indicnlp.tokenize import indic_tokenize
import fasttext.util
import fasttext
import math
from torch.utils.data import DataLoader, Dataset
# Download the Hindi word vectors
# fasttext.util.download_model('hi', if_exists='ignore')

from tqdm import tqdm
import torch.optim as optim
from torch.amp import autocast, GradScaler

In [5]:
import torch
import pandas as pd
import numpy as np
import spacy
import fasttext
import pkg_resources

print("torch:", torch.__version__)
print("pandas:", pd.__version__)
print("numpy:", np.__version__)
print("spacy:", spacy.__version__)

# fasttext version (more reliable this way)
print("fasttext:", pkg_resources.get_distribution("fasttext").version)

# indic-nlp-library version (best via pkg_resources)
print("indic-nlp-library:", pkg_resources.get_distribution("indic-nlp-library").version)

# tqdm version
print("tqdm:", pkg_resources.get_distribution("tqdm").version)

torch: 2.10.0+cu128
pandas: 2.2.2
numpy: 2.0.2
spacy: 3.8.11
fasttext: 0.9.3
indic-nlp-library: 0.92
tqdm: 4.67.3

/tmp/ipykernel_8680/3936933076.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

In [ ]:
with open('2_merged_train_only (1).json','r') as f:
  train_data=json.load(f)

In [ ]:
train_data

{'English-Bengali': {'Train': {'78683': {'source': 'Do not forget to visit the point where the Narmada flowing through the marble rocks interchanges its calmness and serenity into insouciance.',
    'target': 'এই জায়গাগুলো দেখতে ভুলো না যেখানে নর্মদা নদী মার্বেল পাথরের পাহাড়ের মধ্য দিয়ে প্রবাহিত হচ্ছে এবং নিজের শান্তি ও সৌন্দর্যকে অনাসক্তিতে পরিণত করছে।'},
   '78684': {'source': 'It is evident that the biggest cause of poverty is illiteracy .',
    'target': 'এই কথা স্পষ্ট যে দরিদ্রতার বড় কারণ হল অশিক্ষা ।'},
   '78685': {'source': 'The film was released theatrically on 12 April 2013.',
    'target': 'চলচ্চিত্রটি ২০১৩ সালের ১২ই এপ্রিল প্রেক্ষাগৃহে মুক্তি পায়।'},
   '78686': {'source': "is wyatt's birthday party at ten p. m.",
    'target': 'অনিমেষ এর জন্মদিনের পার্টি রাত দশটায়'},
   '78687': {'source': 'Apart from being used as an eatable, barley is also used in many other fields like industries and agriculture.',
    'target': 'খাদ্যদ্রব্য ছাড়াও যব আরো বিভিন্ন ক্ষেত্রে যেমন শিল্প ও কৃষিতে ব্যবহার করা হয়।'},
   '78688': {'source': 'Emperor Akbar got the State Museum constructed during his trip to Ajmer .',
    'target': 'রাজকীয় সংগ্রহালয়ের নির্মাণ সম্রাট আকবর নিজের আজমের যাত্রার সময় করান ׀'},
   '78689': {'source': 'initiate the music on the electronic playlist',
    'target': 'ইলেক্ট্রনিক প্লেলিস্টের গানগুলো শুরু কর'},
   '78690': {'source': 'Srinagar is at a distance of 305 kms from Jammu .',
    'target': 'জম্মু থেকে শ্রীনগরের দূরত্ব হল ৩০৫ কি.মি. ৷'},
   '78691': {'source': 'A devotee is chosen and a Karaga or a clay pot is placed on his head.',
    'target': 'একটি ভক্ত বাছা হয়েছিল এবং একটি কারাগা অথবা একটি কাদা পাত্র তার মাথায় রাখা হয়েছিল।'},
   '78692': {'source': 'The city is lined up with shops that have everything you need to stock up your kitchen shelves with.',
    'target': 'শহরটিতে আপনার রান্নাঘর ভর্তি করার জন্য দোকান সাজানো আছে।'},
   '78693': {'source': 'We can express our feelings and unwind ourselves in many different ways, share our feelings with those whom we know and trust.',
    'target': 'আমরা আমাদের অনুভব প্রকাশ করতে পারি এবং নিজেদের হাঁপ ছাড়াই অনেক বিভিন্ন রীতিতে, আমরা যাদের চিনি এবং বিশ্বাস করি তাদের সাথে আমাদের অনুভব ভাগ করতে পারি।'},
   '78694': {'source': 'It is used as a common picnic spot by the locals.',
    'target': 'স্থানীয়দের দ্বারা এটা সাধারণ পিকনিকের জায়গা হিসাবে ব্যবহৃত হয়।'},
   '78695': {'source': 'The best way to protect a newly born infant from infection is to lift it after cleaning ones hand with soap beforehand .',
    'target': 'নবজাত শিশুকে সংক্রমণের হাত থেকে বাঁচাতে সবথেকে ভালো উপায় হল সাবান দিয়ে হাত ধুয়ে বাচ্চাকে কোলে নেওয়া ׀'},
   '78696': {'source': 'The various categories of persons having different risk behaviours, who report to NICD for HIV testing are given pre-test, post test and continuum of counseling, as per individual case merit.',
    'target': 'বিভিন্ন ধরনের লোকেরা যাদের নানা কার্জকলাপ আছে তারা এন আই সি ডি কে রিপোর্ট করে এইচ আই ভি টেষ্ট করার জন্য তাদের প্রি-টেষ্ট,পোষ্ট-টেষ্ট বা ক্রমাগত উপদেশ দেওয়া হয়ে জন প্রতি কেসের মেরিট দেখে।'},
   '78697': {'source': 'The 2006 Varanasi bombings were a series of bombings that occurred across the Hindu holy city of Varanasi on 7 March 2006.',
    'target': '২০০৬ সালের বারাণসী বোমা হামলা ছিল হিন্দুদের পবিত্র শহর বারাণসীতে ২০০৬ সালের ৭ই মার্চে ঘটা ধারাবাহিক বোমা হামলা।'},
   '78698': {'source': 'One of the legends relating to Eklingji is that after killing Vrakshasur,Indra had meditated and prayed to Eklingji in penitence and to get rid of the curse.',
    'target': 'একলিঙ্গজী সম্পর্কিত কিংবদন্তীগুলির একটি হল যে ভ্রক্ষাসুরকে বধ করার পর ইন্দ্র অভিশাপ থেকে মুক্তি পাওয়ার জন্য অনুশোচনায় ধ্যান করেছিলেন এবং একলিঙ্গজীর কাছে প্রার্থনা জানিয়েছিলেন।'},
   '78699': {'source': 'good food', 'target': 'ভাল খাবার'},
   '78700': {'source': 'This is thought to be very profitable in all important entertaining areas .',
    'target': 'এটাকে অন্যান্য সমস্ত মনোরঞ্জক ক্ষেত্রেও লাভজনক মনে করা হয়েছে ৷'},
   '78701': {'source': 'Among the dead were Black Kettle and his wife. The massacre is remembered as the Battle of the Washita, commemorated by Washita Battlefield National Historic Site.',
    'target': 'মৃতদের মধ্যে ছিল ব্ল্যাক কেটল এবং তার স্ত্রী,এই বেপরোয়া হত্যাকান্ড হয়েছিল ওয়াহিটা যুদ্ধক্ষেত্রে ন্যাশানাল হিস্টোরিক সাইট।'},
   '78702': {'source': 'There is an old palace and Shiva temple in Nadaun .',
    'target': 'নাডৌনে একটা পুরানো মহল এবং একটা শিব মন্দির আছে ।'},
   '78703': {'source': 'let me know about current traffic in carmen drive',
    'target': 'ফটিকছড়ি বর্তমান ট্রাফিক সম্পর্কে আমাকে জানান'},
   '78704': {'source': 'Many of the country’s top places to eat are nestled into remote, rural countryside, and even the tiniest villages boast gourmet farmers’ markets.',
    'target': 'দেশের বিভিন্ন খাবার জায়গাগুলি আছে দূরের গ্রামে ,এছাড়া ছোটো ছোটো গ্রামগুলিতে আছে চাষীদের বাজার ।'},
   '78705': {'source': 'Here one can see the processing of the world famous Darjeeling tea.',
    'target': 'এখানে একজন বিশ্ব বিখ্যাত দার্জিলিং চায়ের প্রক্রিয়াকরণ দেখতে পারেন ।'},
   '78706': {'source': 'It belongs to the Hinayana Buddhism sect in Maharashtra.',
    'target': 'এটি মহারাষ্ট্রের হীনযান বৌদ্ধ সম্প্রদায়ের অন্তর্গত।'},
   '78707': {'source': 'Reading in bright light in the night or working excessively is also dangerous for the eyes .',
    'target': 'রাতে তীব্র আলোতে পড়াশোনা করা বা বেশি কাজ করাও হল চোখের পক্ষে ক্ষতিকারক ৷'},
   '78708': {'source': 'Silk was used in weft designs and in the borders, whereas cotton was used in the body of the fabric.',
    'target': 'ওয়েফট ডিজাইনে এবং পাড়ে সিল্ক ব্যবহার করা হত, আর কাপড়ের জমিতে সুতি ব্যবহার করা হত।'},
   '78709': {'source': 'Some men may experience urinary frequency, urgency and incontinence but this will settle by the third month after surgery.',
    'target': 'যাইহোক,যার ভাইরাস আছে পুনরায় সংক্রামিত হওয়ার সম্ভাবনা খুব কম কারণ শরীরে ভাইরাসের প্রতি প্রতিরোধ ক্ষমতা গড়ে ওঠে।'},
   '78710': {'source': 'change the radio station',
    'target': 'বেতার কেন্দ্র পরিবর্তন করুন'},
   '78711': {'source': 'Various products and techniques were exhibited by total 504 stalls along with 129 big stalls in the farmers fair and agricultural industry exhibition .',
    'target': 'বিগত তিন মাসে জনপদ চম্পাবত এবং পিথৌরাগড়ে অবস্থিত কৃষি বিজ্ঞান কেন্দ্রের বৈজ্ঞানিক উপদেশ সমিতির ( স্যাক ) বৈঠক লোহাঘাট কৃষি বিজ্ঞান কেন্দ্রে ২০১০-এর ২৫শে ফেব্রুয়ারী এবং গৈনা আঞ্চলি কৃষি বিজ্ঞান কেন্দ্রে ২০১০-এর ২৬শে ফেব্রুয়ারী আয়োজন করা হয় ৷'},
   '78712': {'source': 'Most of them are of dietary origin.',
    'target': 'বেশীর ভাগ গুলি আহারের কারনে হয়.'},
   '78713': {'source': 'Every year in the month of Shravana (July-August), when the moon is full, thousands of devout pilgrims gather before Amarnath Cave in the picturesque Lidder Valley in Kashmir to offer their prayers to Lord Shiva.',
    'target': 'প্রত্যেক বছর শ্রাবণ মাসের (জুলাই-আগস্ট) পূর্ণিমায় হাজার হাজার পুণ্যার্থী কাশ্মীরের অসাধারণ সুন্দর লিডার ভ্যালীর অমরনাথ মন্দিরের সামনে জড়ো হয় শিবঠাকুরের কাছে প্রার্থনা করার জন্য।'},
   '78714': {'source': 'Lost people are calling to their friends in their language .',
    'target': 'বিচ্ছিন্ন হয়ে যাওয়া লোক তাদের নিজেদের ভাষায় তাদের লোককে ডাকছে ׀'},
   '78715': {'source': 'Same were given name of `` Yatuman `` in Awesta .',
    'target': 'আবেস্তায় এদের নাম দেওয়া হয়েছে “ রাক্ষস ” ।'},
   '78716': {'source': 'Other than this occurrence of cramps in a certain nerve fiber located in the lower part of the back is also a very important cause .',
    'target': 'এ ছাড়াও একটি গুরুত্বপূর্ণ কারণ হল পিঠের নিচের অংশে স্থিত কোনও স্নায়ু তন্তুর ওপরে টান পড়া ৷'},
   '78717': {'source': 'In the initial years fruit production is less but later on productivity increases gradually .',
    'target': 'প্রথম বছরে ফল উত্পাদন কম হয় কিন্তু পরের বছরগুলিতে উত্পাদনক্ষমতা ধীরে - ধীরে বাড়তে থাকে ৷'},
   '78718': {'source': 'Described by the Indian classical poet, Tagore as a "tear on the face of eternity", the Taj Mahal is undoubtedly the zenith of Moghal architecture and quite simply one of the world\'s most marvelous buildings.',
    'target': 'ভারতীয় প্রাচীন কবি ঠাকুরের বিবরন "অনন্তকাল চোখের জল" তাজমহল নিঃসন্দেহে মোঘল স্থাপত্যের উজ্জ্বল বিন্দু এবং সাধারনভাবে পৃথিবীর সুন্দরতম স্থাপত্যের অন্যতম।'},
   '78719': {'source': 'Therefore in the hilly areas of India we have started strawberry cultivation .',
    'target': 'এই কারণে ভারতে পাহাড়ি অঞ্চলগুলিতে স্ট্রবেরির চাষ করা হচ্ছে ৷'},
   '78720': {'source': 'The park also features the Marine Natural Study Center (tel. 0-7521-0664) and the Tourist Service Center.',
    'target': 'হ্রদটির মধ্যস্থলে একটি পর্বত এটিকে দুই ভাগে বিভক্ত করেছে যার ফলে এর নাম হয়েছে থালে সং হং।'},
   '78721': {'source': 'please set a reminder in my calendar for my meeting on march twenty five',
    'target': 'আমার পঁচিশে মার্চের বৈঠকের জন্য অনুগ্রহ করে আমার ক্যালেন্ডারে একটি অনুস্মারক সেট করুন'},
   '78722': {'source': 'Cross-sectional data were analyzed for 5692 children from Andhra Pradesh State in India and Vietnam sampled within "sites" (20 from each country) and then within "communities" (31 from Vietnam and 102 from India).',
    'target': 'পরীক্ষাজোগ্য তথ্য পরীক্ষীত হয় ৫৬৯২ বাচ্চাদের জন্য ভারতের রাজ্য অন্ধ্রপ্রদেশের এবং ভিয়েতনামের বিভিন্ন স্থান(দেশ প্রতি ২০টি) এবং বিভিন্ন সামাজিক ক্ষেত্র(ভিয়েতনামের থেকে ৩১টি এবং ভারতের থেকে ১০২ টি) থেকে তথ্য গৃহিত হয়।'},
   '78723': {'source': 'But then suddenly Shivaji tore his stomach with a Baghnakha .',
    'target': 'কিন্তু তখনই শিবাজী তাঁর বাঘনখ দিয়ে আফজল খাঁর পেট ছিড়ে দেন ৷'},
   '78724': {'source': 'Walk on the green lawns of this tomb and then drive towards the Akshardam temple, the temple that claims to be the bastion of Hinduism in India.',
    'target': 'এই সমাধির সবুজ লনে হাঁটুন এবং পক্ষরধাম মন্দিরের দিকে গাড়ি চালান, যে মন্দিরটি ভারতে কড়া হিন্দুত্বের আখড়া হিসাবে প্রখ্যাত।'},
   '78725': {'source': 'It is not irrelevant to say that Bharat Muni mentioned Samavakaar , Ihamrig , Dim Vyayog , Utsrishtikak , etc ten type of plays in Natyashashtra .',
    'target': 'এখানে উল্লেখযোগ্য যে ভরত মুণি নাট্যশাস্ত্রে সমওকার , ইহামৃগ , ডিম , ব্যাযোগ , উত্সৃষ্টিকাক ইত্যাদি দশ প্রকারের নাটকের উল্লেখ করা হয়েছে ।'},
   '78726': {'source': 'You will not get beer like this bar to drink in any other bar of Brussels .',
    'target': 'এই ‘ বারের ’ মতো বিয়ার আপনি ব্রসেল্সের অন্য কোনো ‘ বারে ’ পাবেন না ׀'},
   '78727': {'source': 'i want to eat something will you order food for me',
    'target': 'আমি কিছু খেতে চাই আপনি কি আমার জন্য খাবার অর্ডার করবেন'},
   '78728': {'source': 'Recognized by the Government of India and the Kerala Sports Council this institute is also training center of weaponry art called Kalariyapattu .',
    'target': 'ইন্ডিয়ান স্কুল অফ মার্শিয়াল আর্টসে উষিচ্চিলের ( ম্যাসাজ ) জন্য ৬০০ বছরের পুরানো ` এণ্ণত্তোণি ` ( মালিশের ব্যবহৃত বস্তু ) আছে ৷'},
   '78729': {'source': 'The people of New Zealand are also called by the name of Kiwi .',
    'target': 'নিউজিল্যান্ডের লোকেদের কিউয়ি বলেও ডাকা হয় ৷'},
   '78730': {'source': 'One day, the king expressed dissatisfaction with the food she had prepared.',
    'target': 'একদিন, রাজা তাঁর তৈরি করা খাবার নিয়ে অসন্তোষ প্রকাশ করেন।'},
   '78731': {'source': 'Because of its marvellous craft treasure Cracow was called as Polish Rome .',
    'target': 'নিজের অতুলনীয় চমকপ্রদ শিল্পের জন্য ক্রাকোকে পোলিশ রোমা বলা হচ্ছিল ৷'},
   '78732': {'source': 'Buy their beautiful handicrafts, taste their mouth-watering food and return with a treasure trove of pleasant memories.',
    'target': 'তাদের সুন্দর হাতের কাজ,মুখে জল আনা খাবার কেনা এবং তা থেকে স্মৃতিতে ধরে রাখার মতো মূল্যবান সম্পদ পাওয়া যায়।'},
   '78733': {'source': 'In modern times, the tarana is most commonly associated with the singer Amir Khan, who helped popularize it and researched its origins and the syllables used.',
    'target': 'আধুনিক সময়ে, তারানাটি সাধারণত গায়ক আমির খানের সঙ্গে যুক্ত, যিনি এটিকে জনপ্রিয় করতে সাহায্য করেছিলেন এবং এর উৎস ও ব্যবহৃত শব্দাংশ নিয়ে গবেষণা করেছিলেন।'},
   '78734': {'source': 'The true extent of the vectors is still unknown.',
    'target': 'ভেক্টরের প্রকৃত মাত্রা এখনও অজানা।'},
   '78735': {'source': 'Iron : - Is important for synthesis of green color ( chlorophyll ) and maintenance .',
    'target': 'লোহা : গাছে সবুজ রঙের ( ক্লোরেফিল ) সংশ্লেষ এবং রক্ষণাবেক্ষণের জন্য প্রয়োজনীয় ৷'},
   '78736': {'source': 'The Goans who would like to get the tourists stay in their house , we will assist them at all the levels starting from subsidy .',
    'target': 'যে গোয়াবাসী নিজেদের বাড়িতে পর্যটকদের থাকতে দিতে চাইবেন তাদের আমরা সাবসিডি থেকে শুরু করে সব রকম সহায়তা করব ׀'},
   '78737': {'source': 'Black pepper is used in the form of main ingredient in kadhi powder , chaat masala , pulao masala , chana masala , meat masala , sambhar masala etc. .',
    'target': 'কারি মশলা , চাট মশলা , পোলাও মশলা , চানা মশলা , মিট মশলা , সাম্ভর মশলা ইত্যাদিতে গোলমরিচ প্রধান উপাদন হিসাবে ব্যবহৃত হয় ৷'},
   '78738': {'source': 'In the eastern direction of the Red Fort there was a filth filled colony where there were Chor Bazar , open urinals and obstacled sewers .',
    'target': 'সংস্কৃতি এবং পর্যটন মন্ত্রী হবার পরে যখন আমি লাল কেল্লাকে গভীরভাবে পর্যবেক্ষণ করার জন্য কেল্লায় যাই তখন আমি ওখানে অনেক জীর্ণ - শীর্ণ জিনিসপত্র দেখি ׀'},
   '78739': {'source': 'The disease of filaria spreads because of the bite of mosquitoes named culecs pipians at night .',
    'target': 'ফাইলেরিয়া রোগ রাতে কিউলেক্স পাইপিওনাস নামক মশা কামড়ালে হয় ׀'},
   '78740': {'source': 'Both of these prevent nutritional anemia .',
    'target': 'এই দুই উপাদান অপুষ্টিজনিত রক্তাল্পতা থেকে রক্ষা করে ৷'},
   '78741': {'source': 'what time is it in new york city',
    'target': 'ঢাকা শহরে কটা বাজে'},
   '78742': {'source': 'Amblyopia is uncommon and, where present, rarely dense.',
    'target': 'অ্যাম্বলিওপিয়া বিরল এবং যেখানে উপস্থিত, খুব কমই গাঢ়।'},
   '78743': {'source': 'cancel my meeting tomorrow',
    'target': 'আগামীকাল আমার meeting বাতিল করুন'},
   '78744': {'source': 'Cut down sugar completely if you are a clear cut diabetic case.',
    'target': 'যদি আপনার নিশ্চিতভাবে মধুমেহ থাকে আপনার সম্পূর্ণভাবে চিনি ত্যাগ করতে হবে।'},
   '78745': {'source': 'The feathers impart substantial drag, causing the shuttlecock to decelerate greatly over distance.',
    'target': 'পালকগুলি যথেষ্ট পরিমাণে টান প্রযুক্ত করে, যার ফলে দূরত্বের সাথে সাথে শাটলককের গতি অনেক হ্রাস পেয়ে যায়।'},
   '78746': {'source': 'How much money do I have left in my Freecharge wallet?',
    'target': 'আমার ফ্রিচার্জ ওয়ালেটে আমার কত টাকা বাকি আছে?'},
   '78747': {'source': 'Symptom :- Heart becomes weak because of too much hard work or weakness .',
    'target': 'লক্ষণ - অধিক পরিশ্রম অথবা ক্ষীণতার ফলে হৃদয় দুর্বল হয়ে পড়ে ৷'},
   '78748': {'source': 'Participating in the Maha Shivratri festival is also a unique festival.',
    'target': 'মহা শিবরাত্রি উৎসবে অংশগ্রহণ করাও এক অনন্য উৎসব।'},
   '78749': {'source': 'According to historical records , this temple was built sometime in the 12th century.',
    'target': 'শিব মন্দিরটি অবস্থিত ভারতের মধ্যপ্রদেশের ভোজপুরে যেটি ভারতের মধ্যপ্রদেশের মন্দিরগুলি পরিদর্শণকালে অবশ্যদর্শণীয়।'},
   '78750': {'source': 'The ruins of ancient Patliputra inside the borders of the Patna City can be seen even today .',
    'target': 'প্রাচীন পাটালিপুত্রের ভগ্নাবশেষ পাটনা শহরের সীমার ভেতর আজও দেখা যায় ׀'},
   '78751': {'source': 'Rafi stated that he was only so keen to sing with Lata as she was with him.',
    'target': 'রফি বলেন যে তিনি শুধু লাতার সাথে গান গাইতে খুব আগ্রহী ছিলেন কারণ তিনি তাঁর সাথে ছিলেন।'},
   '78752': {'source': 'A very important study in Bangladesh has traced the relationship between risk of death and degrees of wasting and stunting.',
    'target': 'বাংলাদেশের একটা খুবই গুরুত্বপূর্ণ পর্যবেক্ষনে রুপরেখা তৈরী করা হয়েছে মৃত্যুর ঝুঁকি এবং তীব্রতার মধ্যে মধ্যে সর্ম্পক বৃদ্ধি ব্যহত ও দুর্বলতার মতো।'},
   '78753': {'source': 'With 3 wickets in the second innings, he took his maiden 10-wicket haul in first-class cricket, a feat he would later achieve twice in Test cricket.',
    'target': 'দ্বিতীয় ইনিংসে ৩ উইকেট নিয়ে, প্রথম-শ্রেণীর ক্রিকেটে তিনি তাঁর সর্বপ্রথম ১০-উইকেট অর্জন করেন, যে কীর্তি তিনি পরে টেস্ট ক্রিকেটে দুইবার লাভ করেছিলেন।'},
   '78754': {'source': 'You or the cashier can scan this bar code.',
    'target': 'আপনি বা কোষাধ্যক্ষ এই বার কোডটি স্ক্যান করতে পারেন।'},
   '78755': {'source': 'The Rajputs reciprocate the trust and arrange to have Padmini sit in a room at the edge of a water tank.',
    'target': 'রাজপুতরা আস্থার প্রতিদান দেয় এবং পদ্মিনীকে একটি জলাধারের কিনারায় একটি ঘরে বসানোর ব্যবস্থা করে।'},
   '78756': {'source': 'At the confluence with the Sutlej river, Harike barrage was constructed to divert the combined water flows of both rivers to irrigation canals to serve Rajasthan and Punjab areas.',
    'target': 'শতদ্রু নদীর সঙ্গমস্থলে, রাজস্থান এবং পঞ্জাব অঞ্চলের সেচের খালে উভয় নদীর সম্মিলিত জলপ্রবাহকে নিয়ে যাওয়ার জন্য হরিকে বাঁধ নির্মাণ করা হয়েছিল।'},
   '78757': {'source': 'Due to the tension started in the beginning of the January import of onion which is imported from the Pakistan via the way of the Wagha-Atari has got affected .',
    'target': 'জানুয়ারীর শুরুতে এই উত্তেজনা চলাকালীন বাঘা - আটারীর রাস্তা দিয়ে পাকিস্তান থেকে পেঁয়াজের আমদানী প্রভাবিত হয়েছে ।'},
   '78758': {'source': 'In case of water formation in the belly , on being tested by the tapping method the finger feels the pressure of the water .',
    'target': 'পেটে জল হলে ও তা টিপে দেখলে আঙুলে যেন কোনো তরল পদার্থের ধাক্কা লাগছে বলে মনে হয় ׀'},
   '78759': {'source': 'Some areas that are popular for climbing, for example in the United States and Australia, are also sacred places for indigenous peoples.',
    'target': 'কিছু কিছু অঞ্চল যা পর্বতারোহণের জন্য জনপ্রিয়, উদাহরণস্বরূপ মার্কিন যুক্তরাষ্ট্র ও অস্ট্রেলিয়া, আদিবাসীদের জন্যও পবিত্র স্থান।'},
   '78760': {'source': 'There are only 2-3 hotels in Auli wherein it is important to book rooms beforehand .',
    'target': 'ঔলিতে দুটো - তিনটে হোটেল আছে - যেখানে আগে থেকে ঘর বুকিং করাতে হয় ৷'},
   '78761': {'source': 'This is a good solution for those who can tolerate contact lenses.',
    'target': 'যারা কন্টাক্ট লেন্স সহ্য করতে পারেন তাদের জন্য এটি একটি ভাল সমাধান।'},
   '78762': {'source': 'Nausea starts occurring .', 'target': 'ঢেঁকুর ওঠে ৷'},
   '78763': {'source': 'To see the culture of Rajasthani village in Jaipur there can be no better place than ` Chokhi Dhani ` .',
    'target': 'জয়পুরে রাজস্থানী গ্রামের সংস্কৃতি দেখতে চাইলে চোখী ঢাণীর থেকে ভালো জায়গা আর হতে পারে না ׀'},
   '78764': {'source': 'During this time, some martial arts systems devolved to the point that they became popular forms of martial art storytelling entertainment shows.',
    'target': 'এই সময়ে, কিছু মার্শাল আর্ট পদ্ধতি এতটাই উন্নত হয়েছিল যে সেগুলি মার্শাল আর্ট গল্প বলার বিনোদনমূলক অনুষ্ঠানের জনপ্রিয় রূপ হয়ে উঠেছিল।'},
   '78765': {'source': 'Cricket is the most popular sport in Maharashtra.',
    'target': 'মহারাষ্ট্রের সর্বাধিক জনপ্রিয় খেলা হল ক্রিকেট।'},
   '78766': {'source': 'Gauda Jagor is an impression of social life, that displays all the existing moods and modes of human characters.',
    'target': 'গৌড় জাগোর সামাজিক জীবনের একটি ছাপ, যা মানব চরিত্রের সমস্ত বিদ্যমান মেজাজ এবং রীতিকে প্রদর্শন করে।'},
   '78767': {'source': 'This is the reason that in this area idols related to Vaishnav , Shaiv , Buddhist , and Hindu religion are found .',
    'target': 'কুর্কীহার আর আশেপাশের শিল্পকাররা যথেষ্ট সংখ্যায় মূর্তি নির্মাণ করতেন ৷'},
   '78768': {'source': 'Baijnath has 5th place in Dwadash Jyotirlingas .',
    'target': 'দ্বাদশ জ্যোর্তিলিঙ্গের মধ্যে বৈজনাথের স্থান ছিল পঞ্চম ৷'},
   '78769': {'source': 'Indeed cinema and television are still images only , even it would be better to say that this is a chain of still images .',
    'target': 'সিনেমা আর টেলিভিশনে , আসলে , স্থির চিত্র ( Still Images ) - ই হয় , বরং এটা বলা বেশি সঠিক হবে যে স্থির চিত্রের এটি এক শৃঙ্খলা ৷'},

In [ ]:
source_sentences_train=[]
target_sentences_train=[]
id_train=[]

source_sentences_test=[]
target_sentences_test=[]
id_test=[]

In [ ]:
for language_pair, language_data in train_data.items():
    if(language_pair == "English-Hindi"):
      print(f"Language Pair: {language_pair}")
      for data_type, data_entries in language_data.items():
          print(f"  Data Type: {data_type}")
          for entry_id, entry_data in data_entries.items():
              source = entry_data["source"]
              target = entry_data["target"]
              if (data_type == "Test"):
                source_sentences_test.append(source)
                target_sentences_test.append(target)
                id_test.append(entry_id)
              else:
                source_sentences_train.append(source)
                target_sentences_train.append(target)
                id_train.append(entry_id)

Language Pair: English-Hindi
  Data Type: Train

In [ ]:
len(source_sentences_train)

92340

In [ ]:
source_sentences_train[80797]

'Somebody on this side, what will be my goal-test?'

In [ ]:
target_sentences_train[80796]

'रसोईघर की बत्तियाँ बंद करें'

In [ ]:
target_sentences_train[80797]

['इस पक्ष में कोई, मेरे लक्ष्य परीक्षण क्या होगा?']

In [ ]:
ee=target_sentences_train[90000]

In [ ]:
len(target_sentences_train)

92340

In [ ]:
len(id_train)

92340

In [ ]:
train_x={'English':source_sentences_train,'Hindi':target_sentences_train}

In [ ]:

df=pd.DataFrame(train_x)

In [ ]:
df

,English,Hindi
0,cancel everything on my calendar,मेरे कैलेंडर पर सब कुछ रद्द करें
1,Adrenal hormone levels are at their peak durin...,अधिवृक्क के हार्मोन का स्तर प्रातःकाल में अपने...
2,"Golden threads are obtained from Surat, the qu...","स्वर्ण धागे सूरत से प्राप्त होते हैं, जिनकी गु..."
3,Look for agglutination within 30 seconds.,30 सेकेण्ड के भीतर एग्लूटिनेशन देखें।
4,The non-pompousness and informality of their l...,उनके जीवन की आडंबरहीनता एवं अनौपचारिकता उनके स...
...,...,...
80792,"So, is it that this is the optimization proble...","तो, यह अनुकूलन समस्या है जिसमें हम रुचि रखते थे।"
80793,In this Masjid made with red stones there are ...,लाल पत्थरों से बनायी गयी इस मस्जिद में हिन्दू ...
80794,"He began to work on the movie on August 17, 20...","उन्होंने 17 अगस्त, 2010 को फिल्म पर काम करना श..."
80795,start a new shopping list,एक नई खरीदारी सूची शुरू करें
80796,turn off the lights in the kitchen,रसोईघर की बत्तियाँ बंद करें

In [ ]:

def preprocess_and_remove_punctuation(sentence):
    sentence = ''.join([char for char in sentence if char not in string.punctuation and not char.isdigit()])
    return sentence

In [ ]:
def preprocess(sentences):
  tokenized_sentences=[]
  for sentence in sentences:
    doc=nlp(sentence)
    tokenized_sentences.append([token.text for token in doc])
  return tokenized_sentences

In [ ]:
english_train_tokens = preprocess(source_sentences_train)
english_test_tokens=preprocess(source_sentences_test)

In [ ]:
len(english_train_tokens)

92340

In [ ]:
len(english_test_tokens)

23085

In [ ]:
with open('english_train_tokens','wb') as f:
  pickle.dump(english_train_tokens,f)

with open('english_test_tokens','wb') as f:
  pickle.dump(english_test_tokens,f)

In [6]:
with open('/content/drive/MyDrive/english_train_tokens','rb') as f:
  english_train_tokens_1=pickle.load(f)

with open('/content/drive/MyDrive/english_test_tokens','rb') as f:
  english_test_tokens_1=pickle.load(f)

In [7]:
len(english_train_tokens_1)

92340

In [8]:
len(english_test_tokens_1)

23085

In [ ]:
def preprocess_hindi(sentences):
    tokenized_sentences = []
    for sentence in sentences:
        tokens = indic_tokenize.trivial_tokenize_indic(sentence)
        tokenized_sentences.append(tokens)
    return tokenized_sentences

In [ ]:
len(target_sentences_train)

92340

In [ ]:

target_sentences_train_cleaned = [
    s[0] if isinstance(s, list) and len(s) == 1 else s
    for s in target_sentences_train
]


def preprocess_hindi(sentences):
    tokenized_sentences = []
    for sentence in sentences:
        tokens = indic_tokenize.trivial_tokenize_indic(sentence)
        tokenized_sentences.append(tokens)
    return tokenized_sentences

# Tokenize
hindi_tokens = preprocess_hindi(target_sentences_train_cleaned)

In [ ]:
len(hindi_tokens)

92340

In [ ]:
with open('/content/drive/MyDrive/ff_hindi_train_tokens','wb') as f:
  pickle.dump(hindi_tokens,f)

In [10]:
with open('/content/drive/MyDrive/hindi_train_tokens','rb') as f:
  hindi_tokens_1=pickle.load(f)

In [ ]:
len(hindi_tokens_1)

92340

# Encode and padding

In [11]:
en_train=english_train_tokens_1
en_test=english_test_tokens_1
hi_train=hindi_tokens_1

In [12]:
def build_vocab(datasets, specials=["<PAD>", "<SOS>", "<EOS>", "<UNK>"]):
    vocab = set()
    for ds in datasets:
        for sent in ds:
            vocab.update(sent)

    vocab -= set(specials)
    idx2word = specials + sorted(list(vocab))
    word2idx = {w: i for i, w in enumerate(idx2word)}
    return idx2word, word2idx

In [13]:

en_index2word, en_word2index = build_vocab([en_train, en_test])

hi_index2word, hi_word2index = build_vocab([hi_train])

In [ ]:
len(en_index2word)

80335

In [14]:

def encode_and_pad_fixed(sentences, word2index, max_length, device):

    encoded_tensors = []

    for sent in sentences:
        encoded = [word2index["<SOS>"]] + \
                  [word2index.get(word, word2index["<UNK>"]) for word in sent] + \
                  [word2index["<EOS>"]]


        if len(encoded) > max_length:
            encoded = encoded[:max_length]

        else:
            encoded += [word2index["<PAD>"]] * (max_length - len(encoded))

        encoded_tensors.append(torch.tensor(encoded, dtype=torch.long))


    padded = torch.stack(encoded_tensors)
    return padded.to(device)


device='cuda' if torch.cuda.is_available() else 'cpu'

max_len = 50  # manually chosen
en_train_tensor = encode_and_pad_fixed(en_train, en_word2index, max_len, device)
hi_train_tensor = encode_and_pad_fixed(hi_train, hi_word2index, max_len, device)


print("English train shape:", en_train_tensor.shape)
print("Hindi train shape:", hi_train_tensor.shape)

English train shape: torch.Size([92340, 50])
Hindi train shape: torch.Size([92340, 50])

# Embeddings

In [ ]:
!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.hi.300.bin.gz

--2026-03-17 06:35:55--  https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.hi.300.bin.gz
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 65.8.76.77, 65.8.76.47, 65.8.76.35, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|65.8.76.77|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4371554972 (4.1G) [application/octet-stream]
Saving to: ‘cc.hi.300.bin.gz’

cc.hi.300.bin.gz    100%[===================>]   4.07G  6.82MB/s    in 5m 31s

2026-03-17 06:41:26 (12.6 MB/s) - ‘cc.hi.300.bin.gz’ saved [4371554972/4371554972]

In [ ]:
!gunzip cc.hi.300.bin.gz

In [15]:
def load_glove_embeddings(glove_path):
    embeddings_index = {}
    with open(glove_path, encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            coefs = np.asarray(values[1:], dtype='float32')
            embeddings_index[word] = coefs
    print(f"Loaded {len(embeddings_index)} word vectors from GloVe.")
    return embeddings_index

glove_path = '/content/drive/MyDrive/glove.6B.300d.txt'
glove_embeddings = load_glove_embeddings(glove_path)

Loaded 400000 word vectors from GloVe.

In [ ]:
model = fasttext.load_model('cc.hi.300.bin')

In [ ]:
vector = model.get_word_vector('भारत')

In [ ]:
vector.shape

(300,)

In [ ]:
embedding_dim = 300
vocab_size = len(hi_word2index)
vectors = []

for word, idx in hi_word2index.items():
    vectors.append(model.get_word_vector(word))


fas_hi_embeddings = torch.tensor(vectors, dtype=torch.float32)


torch.save(fas_hi_embeddings, "/content/drive/MyDrive/fas_hi_embeddings.pt")

/tmp/ipykernel_9707/671678335.py:9: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:253.)
  fas_hi_embeddings = torch.tensor(vectors, dtype=torch.float32)

In [29]:
# Load back
save_path_hi = '/content/drive/MyDrive/fas_hi_embeddings.pt'
fas_hi_embeddings = torch.load(save_path_hi)

In [30]:
fas_hi_embeddings.shape

torch.Size([82593, 300])

In [31]:
len(hi_word2index)

82593

# encoding and masks

In [ ]:
def encode_and_pad(vocab, sent, max_length):
    sos = vocab["<SOS>"]
    eos = vocab["<EOS>"]
    pad = vocab["<PAD>"]
    unk = vocab["<UNK>"]


    encoded = [vocab.get(w, unk) for w in sent]


    if len(encoded) > max_length - 2:
        encoded = encoded[:max_length - 2]


    padded = [sos] + encoded + [eos]
    padded += [pad] * (max_length - len(padded))
    return padded


max_length_1 = 50


en_train_encoded = [encode_and_pad(en_word2index, s, max_length_1) for s in en_train]
hi_train_encoded = [encode_and_pad(hi_word2index, s, max_length_1) for s in hi_train]

# Model and training

In [25]:

class PositionalEncoding(nn.Module):
    def __init__(self, d_model: int, dropout: float = 0.1, max_len: int = 10_000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float32).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2, dtype=torch.float32) * (-math.log(10_000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)  # (1, max_len, d_model)

        self.register_buffer("pe", pe)

    def forward(self, x):
        # x: (batch, seq_len, d_model)
        x = x + self.pe[:, :x.size(1)]
        return self.dropout(x)

In [26]:

class TransformerMT(nn.Module):
    def __init__(self, src_vocab_size, tgt_vocab_size,
                 src_embeddings, tgt_embeddings,
                 src_pad_id=0,tgt_pad_id=0, d_model=300, nhead=6,
                 num_encoder_layers=6, num_decoder_layers=6,
                 dim_feedforward=1024, dropout=0.1):
        super().__init__()
        self.src_pad_id = src_pad_id
        self.tgt_pad_id=tgt_pad_id
        self.d_model = d_model


        self.src_embed = nn.Embedding.from_pretrained(
            src_embeddings, freeze=False, padding_idx=src_pad_id
        )
        self.tgt_embed = nn.Embedding.from_pretrained(
            tgt_embeddings, freeze=False, padding_idx=tgt_pad_id
        )

        self.pos_enc = PositionalEncoding(self.d_model, dropout=dropout)

        self.transformer = nn.Transformer(
            d_model=d_model,
            nhead=nhead,
            num_encoder_layers=num_encoder_layers,
            num_decoder_layers=num_decoder_layers,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True  # (B, T, C)
        )

        self.generator = nn.Linear(d_model, tgt_vocab_size)

    def src_make_pad_mask(self, ids):
        return (ids == self.src_pad_id)  # (B, T)

    def tgt_make_pad_mask(self,ids):
      return (ids==self.tgt_pad_id)

    def make_causal_mask(self, size, device):
        mask = torch.triu(torch.full((size, size), float("-inf"), device=device), diagonal=1)
        return mask

    def forward(self, src_ids, tgt_in_ids):

        src_key_padding_mask = self.src_make_pad_mask(src_ids)
        tgt_key_padding_mask = self.tgt_make_pad_mask(tgt_in_ids)
        tgt_mask = self.make_causal_mask(tgt_in_ids.size(1), device=src_ids.device)


        src_emb = self.pos_enc(self.src_embed(src_ids) * math.sqrt(self.d_model))
        tgt_emb = self.pos_enc(self.tgt_embed(tgt_in_ids) * math.sqrt(self.d_model))


        out = self.transformer(
            src=src_emb,
            tgt=tgt_emb,
            src_key_padding_mask=src_key_padding_mask,
            tgt_key_padding_mask=tgt_key_padding_mask,
            memory_key_padding_mask=src_key_padding_mask,
            tgt_mask=tgt_mask,
        )
        return self.generator(out)

In [27]:

def build_embedding_matrix(word2idx, pretrained_source, embedding_dim=300, is_fasttext=False):
    vocab_size = len(word2idx)
    embedding_matrix = np.zeros((vocab_size, embedding_dim))


    limit = np.sqrt(6 / embedding_dim)

    for word, idx in word2idx.items():
        try:
            if is_fasttext:
                embedding_matrix[idx] = pretrained_source.get_word_vector(word)
            else:
                embedding_matrix[idx] = pretrained_source[word]
        except (KeyError, AttributeError):

            embedding_matrix[idx] = np.random.uniform(-limit, limit, embedding_dim)

    return torch.tensor(embedding_matrix, dtype=torch.float32)

In [32]:

src_embeddings = build_embedding_matrix(
    en_word2index, glove_embeddings, embedding_dim=300, is_fasttext=False
)


tgt_embeddings = build_embedding_matrix(
    hi_word2index, fas_hi_embeddings, embedding_dim=300, is_fasttext=True
)


model = TransformerMT(
    src_vocab_size=len(en_word2index),
    tgt_vocab_size=len(hi_word2index),
    src_embeddings=src_embeddings,
    tgt_embeddings=tgt_embeddings,
    src_pad_id=en_word2index["<PAD>"],
    tgt_pad_id=hi_word2index["<PAD>"]
)

In [ ]:
!pip install --upgrade torch

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.4.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128

In [ ]:
def train_model(model, train_loader, val_loader, pad_id, num_epochs=10, lr=1e-4, device="cuda"):
    device = torch.device(device if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = model.to(device)
    criterion = nn.CrossEntropyLoss(ignore_index=pad_id)
    optimizer = optim.Adam(model.parameters(), lr=lr)


    scaler = GradScaler(device.type)


    # scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    #     optimizer, mode="min", factor=0.5, patience=3, verbose=True
    # )
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=3
    )

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0


        train_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs} [Train]", leave=False)
        for src, tgt in train_bar:
            src, tgt = src.to(device), tgt.to(device)

            tgt_inp = tgt[:, :-1]
            tgt_out = tgt[:, 1:]

            optimizer.zero_grad()

            with autocast(device_type=device.type, enabled=(device.type == "cuda")):
                logits = model(src, tgt_inp)
                loss = criterion(logits.reshape(-1, logits.size(-1)), tgt_out.reshape(-1))

            if device.type == "cuda":
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                optimizer.step()

            total_loss += loss.item()
            train_bar.set_postfix(loss=loss.item())

        avg_train_loss = total_loss / len(train_loader)


        model.eval()
        val_loss = 0
        val_bar = tqdm(val_loader, desc=f"Epoch {epoch+1}/{num_epochs} [Val]", leave=False)
        with torch.no_grad():
            for src, tgt in val_bar:
                src, tgt = src.to(device), tgt.to(device)
                tgt_inp = tgt[:, :-1]
                tgt_out = tgt[:, 1:]

                with autocast(device_type=device.type, enabled=(device.type == "cuda")):
                    logits = model(src, tgt_inp)
                    loss = criterion(logits.reshape(-1, logits.size(-1)), tgt_out.reshape(-1))
                val_loss += loss.item()
                val_bar.set_postfix(loss=loss.item())

        avg_val_loss = val_loss / len(val_loader)

        print(f"Epoch {epoch+1}/{num_epochs} | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")


        scheduler.step(avg_val_loss)


        save_path = f"/content/drive/MyDrive/frf_transformer_epoch{epoch+1}.pth"
        torch.save(model.state_dict(), save_path)
        print(f" Model saved at {save_path}")

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.amp import autocast, GradScaler
from torch.utils.data import DataLoader, Dataset
import random


class TranslationDataset(Dataset):
    def __init__(self, src_sequences, tgt_sequences):
        self.src = src_sequences
        self.tgt = tgt_sequences

    def __len__(self):
        return len(self.src)

    def __getitem__(self, idx):
        return torch.tensor(self.src[idx], dtype=torch.long), torch.tensor(self.tgt[idx], dtype=torch.long)

def collate_fn(batch, src_pad_id, tgt_pad_id):

    src_batch, tgt_batch = zip(*batch)
    src_batch = nn.utils.rnn.pad_sequence(src_batch, batch_first=True, padding_value=src_pad_id)
    tgt_batch = nn.utils.rnn.pad_sequence(tgt_batch, batch_first=True, padding_value=tgt_pad_id)
    return src_batch, tgt_batch



src = en_train_encoded
tgt = hi_train_encoded


data = list(zip(src, tgt))
random.shuffle(data)
src, tgt = zip(*data)

split_idx = int(0.9 * len(src))
train_src, val_src = src[:split_idx], src[split_idx:]
train_tgt, val_tgt = tgt[:split_idx], tgt[split_idx:]


src_pad_id = en_word2index["<PAD>"]
tgt_pad_id = hi_word2index["<PAD>"]


train_dataset = TranslationDataset(train_src, train_tgt)
val_dataset = TranslationDataset(val_src, val_tgt)

train_loader = DataLoader(
    train_dataset, batch_size=32, shuffle=True,
    collate_fn=lambda b: collate_fn(b, src_pad_id, tgt_pad_id),
    num_workers=4, pin_memory=True
)
val_loader = DataLoader(
    val_dataset, batch_size=32, shuffle=False,
    collate_fn=lambda b: collate_fn(b, src_pad_id, tgt_pad_id),
    num_workers=4, pin_memory=True
)


train_model(
    model,
    train_loader,
    val_loader,
    pad_id=tgt_pad_id,
    num_epochs=10,
    lr=1e-4,
    device="cuda" if torch.cuda.is_available() else "cpu"
)

Using device: cuda

Epoch 1/10 [Train]:   0%|          | 0/2598 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
/usr/local/lib/python3.12/dist-packages/torch/nn/modules/activation.py:1336: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  key_padding_mask = F._canonical_mask(

Epoch 1/10 | Train Loss: 6.0853 | Val Loss: 5.3761
 Model saved at /content/drive/MyDrive/frf_transformer_epoch1.pth

Epoch 2/10 | Train Loss: 5.0798 | Val Loss: 4.9574
 Model saved at /content/drive/MyDrive/frf_transformer_epoch2.pth

Epoch 3/10 | Train Loss: 4.6545 | Val Loss: 4.6996
 Model saved at /content/drive/MyDrive/frf_transformer_epoch3.pth

Epoch 4/10 | Train Loss: 4.3173 | Val Loss: 4.4720
 Model saved at /content/drive/MyDrive/frf_transformer_epoch4.pth

Epoch 5/10 | Train Loss: 4.0128 | Val Loss: 4.2890
 Model saved at /content/drive/MyDrive/frf_transformer_epoch5.pth

Epoch 6/10 | Train Loss: 3.7362 | Val Loss: 4.1168
 Model saved at /content/drive/MyDrive/frf_transformer_epoch6.pth

Epoch 7/10 | Train Loss: 3.4871 | Val Loss: 4.0037
 Model saved at /content/drive/MyDrive/frf_transformer_epoch7.pth

Epoch 8/10 | Train Loss: 3.2649 | Val Loss: 3.8950
 Model saved at /content/drive/MyDrive/frf_transformer_epoch8.pth

Epoch 9/10 | Train Loss: 3.0598 | Val Loss: 3.8193
 Model saved at /content/drive/MyDrive/frf_transformer_epoch9.pth

Epoch 10/10 | Train Loss: 2.8673 | Val Loss: 3.7749
 Model saved at /content/drive/MyDrive/frf_transformer_epoch10.pth

# Testing

In [33]:
import pickle
with open('/content/drive/MyDrive/final_test_df','rb') as f:
  test_data=pickle.load(f)

In [34]:

device='cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
device

'cuda'

In [35]:
source_sentences_test=[]
target_sentences_test=[]
id_val=[]

In [36]:
for language_pair, language_data in test_data.items():
    if(language_pair == "English-Hindi"):
      print(f"Language Pair: {language_pair}")
      for data_type, data_entries in language_data.items():
          print(f"  Data Type: {data_type}")
          for entry_id, entry_data in data_entries.items():
              source = entry_data["source"]
              target = entry_data["target"]
              if (data_type == "Test"):
                source_sentences_test.append(source)
                target_sentences_test.append(target)
                id_val.append(entry_id)
              else:
                source_sentences_train.append(source)
                target_sentences_train.append(target)
                id_train.append(entry_id)

Language Pair: English-Hindi
  Data Type: Test

In [ ]:
len(source_sentences_test)

23085

In [ ]:
len(target_sentences_test)

23085

In [40]:
test_x={'English':source_sentences_test,'Hindi':target_sentences_test}

In [41]:

test_df=pd.DataFrame(test_x)

In [ ]:
test_df

,English,Hindi
0,And then we need to assure students that a com...,[और फिर हम छात्रों को विश्वास दिलाने की जरूरत ...
1,what is the address for the event scheduled on...,[1 जनवरी को आयोजित कार्यक्रम के लिए पता क्या है]
2,Indira Gandhi National Park is spread in an ar...,[इंदिरा गांधी राष्ट्रीय उद्यान कोयंबटूर जिले म...
3,Local musicians also attracted the King's atte...,[स्थानीय संगीतकारों ने भी राजा की ओर ध्यान आकर...
4,"Of course, do some more stuff on this.","[निश्चय ही, इस पर कुछ और काम करें।]"
...,...,...
23080,send an email to peter and ask him how is he n...,[पीटर को एक ई-मेल भेजें और उससे पूछें कि वह कै...
23081,"At Bose ' s initiative , the Government of Ori...",[बोस की पहल से उड़ीसा सरकार ने प्रोफेसर हल्डेन...
23082,"v.After initial opening, store H2O2 at 4oC in ...","[v. आरंभिक खोलने के बाद, एच2ओ2 को 4 डिग्री सेल..."
23083,Holding the claw of the left leg with both han...,[उत्सर्जन के बाद दोनों हाथों से बाएं पैर की पा...
23084,our water bill was too high,[हमारे जल बिल बहुत अधिक था]

In [ ]:
test_df['Hindi']

0        [और फिर हम छात्रों को विश्वास दिलाने की जरूरत ...
1         [1 जनवरी को आयोजित कार्यक्रम के लिए पता क्या है]
2        [इंदिरा गांधी राष्ट्रीय उद्यान कोयंबटूर जिले म...
3        [स्थानीय संगीतकारों ने भी राजा की ओर ध्यान आकर...
4                      [निश्चय ही, इस पर कुछ और काम करें।]
                               ...
23080    [पीटर को एक ई-मेल भेजें और उससे पूछें कि वह कै...
23081    [बोस की पहल से उड़ीसा सरकार ने प्रोफेसर हल्डेन...
23082    [v. आरंभिक खोलने के बाद, एच2ओ2 को 4 डिग्री सेल...
23083    [उत्सर्जन के बाद दोनों हाथों से बाएं पैर की पा...
23084                          [हमारे जल बिल बहुत अधिक था]
Name: Hindi, Length: 23085, dtype: object

In [ ]:

with open('/content/drive/MyDrive/english_train_tokens','rb') as f:
  english_tokens_1=pickle.load(f)

with open('/content/drive/MyDrive/english_test_tokens','rb') as f:
  english_test_1=pickle.load(f)

In [ ]:

with open('/content/drive/MyDrive/hindi_train_tokens','rb') as f:
  hindi_tokens_1=pickle.load(f)

In [ ]:
en_train=english_tokens_1
en_test=english_test_1
hi_train=hindi_tokens_1

In [ ]:
len(english_tokens_1)

92340

In [ ]:
len(english_test_1)

23085

In [ ]:
len(hindi_tokens_1)

92340

In [ ]:
len(en_word2index)

80335

In [ ]:
len(hi_word2index)

82593

In [ ]:

def encode_and_pad_fixed(sentences, word2index, max_length, device):

    encoded_tensors = []

    for sent in sentences:
        encoded = [word2index["<SOS>"]] + \
                  [word2index.get(word, word2index["<UNK>"]) for word in sent] + \
                  [word2index["<EOS>"]]

        if len(encoded) > max_length:
            encoded = encoded[:max_length]
        else:
            encoded += [word2index["<PAD>"]] * (max_length - len(encoded))

        encoded_tensors.append(torch.tensor(encoded, dtype=torch.long))
    padded = torch.stack(encoded_tensors)
    return padded.to(device)

max_len = 50  # manually chosen
en_test_tensor = encode_and_pad_fixed(english_test_1, en_word2index, max_len, device)


print("English test shape:", en_test_tensor.shape)

English test shape: torch.Size([23085, 50])

In [ ]:

def load_glove_embeddings(glove_path):
    embeddings_index = {}
    with open(glove_path, encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            coefs = np.asarray(values[1:], dtype='float32')
            embeddings_index[word] = coefs
    print(f"Loaded {len(embeddings_index)} word vectors from GloVe.")
    return embeddings_index

glove_path = '/content/drive/MyDrive/glove.6B.300d.txt'
glove_embeddings = load_glove_embeddings(glove_path)

Loaded 400000 word vectors from GloVe.

In [23]:
import torch

from tqdm import tqdm
import json


class TestDataset(Dataset):
    def __init__(self, src_data):
        self.src_data = src_data

    def __len__(self):
        return len(self.src_data)

    def __getitem__(self, idx):
        return torch.tensor(self.src_data[idx], dtype=torch.long)


def collate_fn_test(batch, pad_id):
    max_len = max(len(x) for x in batch)
    padded = [torch.cat([x, torch.full((max_len - len(x),), pad_id,dtype=torch.long, device=x.device)]) for x in batch]
    return torch.stack(padded, dim=0)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

pad_id_src = en_word2index["<PAD>"]
pad_id_tgt = hi_word2index["<PAD>"]

model = TransformerMT(
    src_vocab_size=len(en_word2index),
    tgt_vocab_size=len(hi_word2index),
    src_embeddings=src_embeddings,
    tgt_embeddings=tgt_embeddings,
    src_pad_id=pad_id_src,
    tgt_pad_id=pad_id_tgt
).to(device)

checkpoint_path = "/content/drive/MyDrive/frf_transformer_epoch10.pth"
model.load_state_dict(torch.load(checkpoint_path, map_location=device))
print(f"Loaded checkpoint: {checkpoint_path}")


def greedy_decode(model, src, max_len=60, pad_id=0, device="cpu"):
    model.eval()
    batch_size = src.size(0)


    sos_id = 1
    tgt = torch.full((batch_size, 1), sos_id, dtype=torch.long, device=device)

    with torch.no_grad():
        for _ in range(max_len - 1):
            logits = model(src, tgt)   # (B, T, vocab_size)
            next_token = logits[:, -1, :].argmax(-1, keepdim=True)  # (B, 1)
            tgt = torch.cat([tgt, next_token], dim=1)

    return tgt  # (B, max_len)


test_dataset = TestDataset(en_test_tensor)
test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False,
    collate_fn=lambda b: collate_fn_test(b, pad_id_src)
)

save_path = "/content/drive/MyDrive/nnn_est_predictions.json"

all_preds = []

with torch.no_grad():
    for batch in tqdm(test_loader, desc="Decoding", unit="batch"):
        src_ids = batch.to(device)


        batch_preds = greedy_decode(
            model, src_ids, max_len=60, pad_id=pad_id_tgt, device=device
        )


        batch_preds = [seq.tolist() for seq in batch_preds]
        all_preds.extend(batch_preds)


with open(save_path, "w", encoding="utf-8") as f:
    json.dump(all_preds, f, ensure_ascii=False, indent=2)

print(f"Saved test predictions to {save_path}")

In [38]:
import json
with open("/content/drive/MyDrive/nnn_est_predictions.json", "r", encoding="utf-8") as f:
    preds = json.load(f)

In [17]:
!pip install sacrebleu rouge-score

Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.0.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (4.67.3)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 8.3 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=bf70488be5391011aa7cc7ec3c2e96bcca50d40c0741eafe572b08fbf715402e
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: portalocker, colorama, sacrebleu, rouge-score
Successfully installed colorama-0.4.6 portalocker-3.2.0 rouge-score-0.1.2 sacrebleu-2.6.0

In [18]:
!pip install rouge

Collecting rouge
  Downloading rouge-1.0.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from rouge) (1.17.0)
Downloading rouge-1.0.1-py3-none-any.whl (13 kB)
Installing collected packages: rouge
Successfully installed rouge-1.0.1

In [19]:
import sacrebleu
import pkg_resources

print("sacrebleu:", sacrebleu.__version__)
print("rouge-score:", pkg_resources.get_distribution("rouge-score").version)
print("rouge:", pkg_resources.get_distribution("rouge").version)

sacrebleu: 2.6.0
rouge-score: 0.1.2
rouge: 1.0.1

In [42]:
import json
from sacrebleu.metrics import BLEU, CHRF
from rouge import Rouge

# Load raw token-ID predictions
# with open("/content/drive/MyDrive/nnn_est_predictions.json", "r", encoding="utf-8") as f:
#     preds = json.load(f)

# Decode token IDs → Hindi strings
eos_id = hi_word2index["<EOS>"]
pad_id = hi_word2index["<PAD>"]
sos_id = hi_word2index["<SOS>"]

skip_ids = {sos_id, eos_id, pad_id}

decoded_preds = []
for seq in preds:
    tokens = []
    for tok_id in seq:
        if tok_id == eos_id:
            break
        if tok_id not in skip_ids:
            tokens.append(hi_index2word[tok_id])
    decoded_preds.append(" ".join(tokens))

# Clean reference strings
decoded_refs = [
    r[0] if isinstance(r, list) else r
    for r in test_df['Hindi']
]

# Compute metrics
refs_nested = [decoded_refs]

bleu_metric = BLEU()
chrf_metric = CHRF()

bleu = bleu_metric.corpus_score(decoded_preds, refs_nested)
chrf = chrf_metric.corpus_score(decoded_preds, refs_nested)

rouge = Rouge()
scores = rouge.get_scores(decoded_preds, decoded_refs, avg=True)

metrics = {
    "BLEU": bleu.score,
    "chrF": chrf.score,
    "ROUGE-1": scores["rouge-1"]["f"] * 100,
    "ROUGE-2": scores["rouge-2"]["f"] * 100,
    "ROUGE-L": scores["rouge-l"]["f"] * 100
}

print(metrics)

{'BLEU': 9.448198355791833, 'chrF': 31.478134674849905, 'ROUGE-1': 40.91412090337956, 'ROUGE-2': 15.23398518260228, 'ROUGE-L': 35.31283279789}